ERPMBA/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ERPMBA.Models;
using ERPMBA.Controllers;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


namespace ERPMBA.Controllers
{
    public class AdministratorController : Controller
    {
        //
        // GET: /adminstration/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UserAdmin()
        {
            return View();

        }
        public ActionResult Grants()
        {
            return View();

        }
        public JsonResult GetGrantInfo()
        {
            DbconnectionGrant dbcont = new DbconnectionGrant();
            List<Grants> ListofUser = dbcont.Grants.ToList();


            return Json(ListofUser, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public string InsertGrant(Grants usr1)

        {
            DbconnectionGrant dbcont = new DbconnectionGrant();
            var usr = new Grants();

            usr.Userid = usr1.Userid;
            usr.RoleId = usr1.RoleId;
            dbcont.Grants.Add(usr);
            dbcont.SaveChanges();
            return "Employee Inserted";
        }

        public ActionResult ItemAdmin()
        {
            return View();

        }
        public ActionResult CustomerAdmin()
        {
            return View();

        }
        public ActionResult Role()
        {
            return View();

        }
        public JsonResult GetRoleInfo()
        {
            DbconnectionRole dbcont = new DbconnectionRole();
            List<Role> ListofUser = dbcont.RoleClass.ToList();


            return Json(ListofUser, JsonRequestBehavior.AllowGet);

        }
        [HttpPost]
        public string InsertRole(Role usr1)

        {
            DbconnectionRole dbcont = new DbconnectionRole();
            var usr = new Role();

            usr.Inventory = usr1.Inventory;
            usr.HR = usr1.HR;
            usr.CRM = usr1.CRM;
            usr.Dashboard = usr1.Dashboard;
            usr.ITSMS = usr1.ITSMS;
            if (usr.Inventory == "0")
            {
                usr.RoleId = usr1.RoleId;
                usr.RoleName = usr1.RoleName;
                usr.Comments = usr1.Comments;
                usr.Users = "0";
                usr.Stack = "0";
                usr.Product = "0";
                usr.Packages = "0";
                usr.Orders = "0";
                usr.Billing = "0";
                usr.Integration = "0";
                usr.Reports = "0";
                dbcont.RoleClass.Add(usr);
                dbcont.SaveChanges();
                return "Employee Inserted";

            }
            else
            {
                usr.RoleId = usr1.RoleId;
                usr.RoleName = usr1.RoleName;
                usr.Comments = usr1.Comments;
                usr.Users = usr1.Users;
                usr.Stack = usr1.Stack;
                usr.Product = usr1.Product;
                usr.Packages = usr1.Packages;
                usr.Orders = usr1.Orders;
                usr.Billing = usr1.Billing;
                usr.Integration = usr1.Integration;
                usr.Reports = usr1.Reports;
                dbcont.RoleClass.Add(usr);
                dbcont.SaveChanges();
                return "Employee Inserted";

            }

        }

        [HttpPost]
        public string UpdateRole(Role usr1)
        {

            if (usr1 != null)
            {
                using (DbconnectionRole dataContext = new DbconnectionRole())
                {
                    var no = usr1.RoleId;
                    var usr = dataContext.RoleClass.Where(x => x.RoleId == no).FirstOrDefault();

                    usr.RoleId = usr1.RoleId;
                    usr.RoleName = usr1.RoleName;
                    usr.Comments = usr1.Comments;
                    usr.Inventory = usr1.Inventory;
                    usr.Users = usr1.Users;
                    usr.Stack = usr1.Stack;
                    usr.Product = usr1.Product;
                    usr.Packages = usr1.Packages;
                    usr.Orders = usr1.Orders;
                    usr.Billing = usr1.Billing;
                    usr.Integration = usr1.Integration;
                    usr.Reports = usr1.Reports;


                    dataContext.SaveChanges();
                    return "Employee Updated";
                }
            }
            else
            {
                return "Invalid Employee";
            }
        }



        public string DeleteRole(Role usrd)
        {
            if (usrd != null)
            {
                using (DbconnectionRole dataContext = new DbconnectionRole())
                {
                    var no = usrd.RoleId;
                    var UserList = dataContext.RoleClass.Where(x => x.RoleId == no).FirstOrDefault();
                    dataContext.RoleClass.Remove(UserList);
                    dataContext.SaveChanges();
                    return "Employee Deleted";
                }
            }
            else
            {
                return "Invalid Employee";
            }
        }


        public ActionResult SupplierAdmin()
        {
            return View();

        }
        public ActionResult HRAdmin()
        {
            return View();

        }
        public ActionResult UserInf()
        {

            return View();

        }

        public JsonResult GetUserInfo()
        {
            DbconnectionLogin dbcont = new DbconnectionLogin();
            List<Userclass> ListofUser = dbcont.Userclassses.ToList();


            return Json(ListofUser, JsonRequestBehavior.AllowGet);

        }

        public JsonResult getUserInf()
        {
            using (DbconnectionLogin dataContext = new DbconnectionLogin())
            {

                var ListofUsers = dataContext.Userclassses;
                return Json(ListofUsers, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult HR()
        {

            return View();

        }

        [HttpPost]
        public string InsertUsers(Userclass usr1)
        {
            DbconnectionLogin dbcont = new DbconnectionLogin();
            var usr = new Userclass();

            usr.userid = usr1.userid;
            usr.username = usr1.username;
            usr.email = usr1.email;
            usr.firstname = usr1.firstname;
            usr.secondname = usr1.secondname;
            usr.Telephoneno = usr1.Telephoneno;
            usr.password = usr1.password;
            usr.Image_User = usr1.Image_User;

            dbcont.Userclassses.Add(usr);
            dbcont.SaveChanges();

            return "Employee Inserted";

        }





        [HttpPost]
        public string UpdateUser(Userclass usr1)
        {

            if (usr1 != null)
            {
                using (DbconnectionLogin dataContext = new DbconnectionLogin())
                {
                    var no = usr1.userid;
                    var usr = dataContext.Userclassses.Where(x => x.userid == no).FirstOrDefault();

                    usr.userid = usr1.userid;
                    usr.username = usr1.username;
                    usr.email = usr1.email;
                    usr.firstname = usr1.firstname;
                    usr.secondname = usr1.secondname;
                    usr.Telephoneno = usr1.Telephoneno;
                    usr.password = usr1.password;
                    usr.Image_User = usr1.Image_User;


                    dataContext.SaveChanges();
                    return "Employee Updated";
                }
            }
            else
            {
                return "Invalid Employee";
            }
        }



        public string DeleteUser(Userclass usrd)
        {
            if (usrd != null)
            {
                using (DbconnectionLogin dataContext = new DbconnectionLogin())
                {
                    var no = usrd.userid;
                    var UserList = dataContext.Userclassses.Where(x => x.userid == no).FirstOrDefault();
                    dataContext.Userclassses.Remove(UserList);
                    dataContext.SaveChanges();
                    return "Employee Deleted";
                }
            }
            else
            {
                return "Invalid Employee";
            }
        }

        public ActionResult Setting1()
        {

            return View();

        }
        public string DeleteMenu(MenuClass usrd)
        {
            if (usrd != null)
            {
                using (DbconnectionSettings dataContext = new DbconnectionSettings())
                {
                    var no = usrd.MenuId;
                    var UserList = dataContext.MenuApp.Where(x => x.MenuId == no).FirstOrDefault();
                    dataContext.MenuApp.Remove(UserList);
                    dataContext.SaveChanges();
                    return "Employee Deleted";
                }
            }
            else
            {
                return "Invalid Employee";
            }
        }
        public string DeleteSubMenu(MenuChild usrd)
        {
            if (usrd != null)
            {
                using (DbconnectionSettingsChild dataContext = new DbconnectionSettingsChild())
                {
                    var no = usrd.ChildMenuId;
                    var UserList = dataContext.ChildMenuApp.Where(x => x.ChildMenuId == no).FirstOrDefault();
                    dataContext.ChildMenuApp.Remove(UserList);
                    dataContext.SaveChanges();
                    return "Employee Deleted";
                }
            }
            else
            {
                return "Invalid Employee";
            }
        }
        public ActionResult Customer()
        {

            return View();

        }




        public ActionResult Supplier()
        {

            return View();

        }

ERPMBA/Views/Administrator/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Style/MasterPage.cshtml";


}
@section featured{




    <ul class="nav nav-pills" style="background: linear-gradient(to right, #e1eec3, #f05053);">
        <li style="width: 200px;  text-align:center">@Html.ActionLink("Users", "UserInf", "Administrator", new { @style = "color:Black;" })</li>
        <li style="width: 200px;  text-align:center">@Html.ActionLink("Item", "ItemAdmin", "Administrator", new { @style = "color:Black;" })</li>
        <li style="width: 200px;  text-align:center">@Html.ActionLink("Customer", "CustomerAdmin", "Administrator", new { @style = "color:Black;" })</li>
        <li style="width: 200px;  text-align:center">@Html.ActionLink("Supplier", "SupplierAdmin", "Administrator", new { @style = "color:Black;" })</li>
    </ul>

}

ERPMBA/Views/Administrator/UserAdmin.cshtml
@{
    ViewBag.Title = "UserAdmin";
    Layout = "~/Views/Style/MasterPage.cshtml";
}
@section featured{

    <div class="SideDiv">

        <div class="inner-bg">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 text">
                        <center><h1> <u><strong>ITCloudModules.Com</strong></u></h1></center>
                        <div class="description" style="background-color:brown;">


                            </p>
                        </div>

                    </div>

                    <div class="col-sm-4 form-box" style=" background-color: slategray">
                        <div class="form-top">
                            <div class="form-top-left">
                                <h3>Sign up now</h3>
                                <p>Fill in the form below to get instant access:</p>
                            </div>
                            <div class="form-top-right">
                                <i class="fa fa-pencil"></i>

                            </div>

                        </div>
                        <div class="form-bottom">

                            <form role="form" action="" method="post" class="registration-form">
                                <div style=" background-color: lightgrey; padding:20px">
                                    <div class="form-group">
                                        <label for="Name">Name</label>
                                        <label class="sr-only" for="form-first-name">First name</label>
                                        <input type="text" name="form-first-name" placeholder="First name..." class="form-first-name form-control" id="form-first-name" required>
                                    </div>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-last-name">Last name</label>
                                        <input type="text" name="form-last-name" placeholder="Last name..." class="form-last-name form-control" id="form-last-name" required>
                                    </div>
                                    <label for="Name">E-Mail</label>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-email">Email</label>
                                        <input type="text" name="form-email" placeholder="Email..." class="form-email form-control" id="form-email" required>
                                    </div>
                                    <label for="Name">Password</label>
                                    <div class="form-group">
                                        <label class="sr-only" for="form-password">password</label>
                                        <input type="password" name="form-last-name" placeholder="Password..." class="form-password form-control" id="form-password" required>
                                    </div>

                                    <div class="form-group">
                                        <label class="sr-only" for="form-cpassword">Conform Password</label>
                                        <input type="password" name="form-last-name" placeholder="Conform Password..." class="form-password form-control" id="form-cpassword" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="Name">Birthday</label>
                                        <label class="sr-only" for="form-dob">Birthday</label>
                                        <input type="date" aria-controls name="form-last-name" placeholder="Birthday..." class="form-number form-control" id="form-dob">
                                    </div>
                                    <label for="Name">Gender</label>
                                    <div class="form-group">
                                        <label class="sr-only" for="gender">Select Gender</label>
                                        <select class="form-gender form-control" id="gender">
                                            <option value="Male">Male</option>
                                            <option value="Female">FeMale</option>
                                            <div class="container">

                                        </select>

                                        @*  <h1>Bootstrap drop down with country codes</h1>
                                            <p>&nbsp;</p>*@
                                        <div class="form-group" id="country-codes">
                                            <button class="btn btn-primary form-group-toggle" type="button" data-toggle="form-group">
                                                <span class="value">Select a Country</span>
                                                <span class="caret"></span>
                                            </button>
                                            <select>
                                                <ul class="form-group-menu">

                                                    <option><a href="#" value="+91">India(+91)</a></option>
                                                    <option><a href="#" value="+61">australia (+61)</a></option>
                                                    <option><a href="#" value="+86">China (+86)</a></option>
                                                    <option><a href="#" value="+47">Norway (+47)</a></option>
                                                    <option><a href="#" value="+46">Sweeden (+46)</a></option>
                                                    <option><a href="#" value="+79">Danmark (+79)</a></option>
                                                </ul>
                                        </div>
                                    </div>

                                    </select>
                                    <label for="file">Upload your photos :</label>
                                    <input type="file" onchange="onFileSelected(event)">
                                    <img id="myimage" style="height:200px; width:250 ">
                                </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script>

 function onFileSelected(event) {
  var selectedFile = event.target.files[0];
  var reader = new FileReader();

  var imgtag = document.getElementById("myimage");
  imgtag.title = selectedFile.name;

  reader.onload = function(event) {
    imgtag.src = event.target.result;
  };

  reader.readAsDataURL(selectedFile);
}

    </script>
    <br>
    <input type="submit" />
}

ERPMBA/Views/Administrator/UserInf.cshtml
@{
    ViewBag.Title = "UserInf";
    Layout = "~/Views/Style/MasterPage.cshtml";
}
@section featured{

    @Html.Partial("Index")
    <div ng-app="myApp" style="float:left; width:60%;padding-left:50px; padding-top:20px; border-color:#333300">

        <script>

        var myApp = angular.module("myApp", []);


        myApp.controller("Userctrl", function ($scope, $http) {
            $scope.userDetails = "";
            $http.get("/Administrator/GetUserInfo")
            .then(function (collectdata) {
                $scope.userDetails = collectdata.data;
                $scope.editAdd = true;
                $scope.editupdate = false;
                $scope.userDetails1 = false;

            })

            $scope.NewInsert =  {
                NewUsers: {}
            }

            $scope.removeRec = function (User) {
                $http.post("/Administrator/DeleteUser", User)
                 .then(function (data) {
                     location.reload();
                     return response;


                 })
            }

            $scope.EditRecord = function (User) {
                $scope.NewInsert.NewUsers.userid = User.userid;
                $scope.NewInsert.NewUsers.username = User.username;
                $scope.NewInsert.NewUsers.dob = User.dob;
                $scope.NewInsert.NewUsers.email = User.email;
                $scope.NewInsert.NewUsers.firstname = User.firstname;
                $scope.NewInsert.NewUsers.secondname = User.secondname;
                $scope.NewInsert.NewUsers.moblieno = User.moblieno;
                $scope.NewInsert.NewUsers.password = User.password;
                $scope.NewInsert.NewUsers.Telephoneno = User.Telephoneno;
                $scope.NewInsert.NewUsers.Image_User = User.Image_User;

                $scope.userDetails1 = true;
                $scope.editupdate = true;
                $scope.editAdd = false;
                alert("Edit");




            }

            $scope.AddRecord = function () {


                $scope.editAdd = true;
                $scope.userDetails1 = true;

                alert("Add New Record 1");
            }
            $scope.Submit = function () {
                $http.post("/Administrator/InsertUsers",$scope.NewInsert.NewUsers)
                .then(function (data){
                    location.reload();
                              alert("Save Record");

                })
            }


            $scope.Update = function () {
                $http.post("/Administrator/UpdateUser", $scope.NewInsert.NewUsers)
                .then(function (data) {
                    location.reload();
                    alert("Save Update");

                    $scope.editAdd = true;
                    $scope.editupdate = false;

                })
            }
            $scope.ShowUsers = function () {
                alert("Show mE");
            }

            $scope.LoadFileData = function (event) {

                var selectedFile = event.target.files[0];
                var reader = new FileReader();

                var imgtag = document.getElementById("NewInsert.NewUsers.Image_User");
                imgtag.title = selectedFile.name;

                reader.onload = function (event) {
                    imgtag.src = event.target.result;
                    $scope.NewInsert.NewUsers.Image_User = event.target.result;
                };

                reader.readAsDataURL(selectedFile);
            }


        });

        </script>
        <style>
            table, td, tr {
                padding: 10px;
            }
        </style>


        <div ng-controller="Userctrl">

            <div ng-show="userDetails1">
                <h4 style="text-align:center">User Details</h4>
                <table>
                    <tr>
                        <td>

                            User Id
                        </td>
                        <td>
                            <input id="myid" style="width:250px" class="form-control" placeholder="Enter User Id" type="text" ng-model="NewInsert.NewUsers.userid" name="userid">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            User Name
                        </td>
                        <td>
                            <input type="text" style="width:250px" class="form-control" ng-model="NewInsert.NewUsers.username" name="pusername">
                        </td>


                    </tr>
                    <tr>
                        <td>

                            Email Address
                        </td>
                        <td>
                            <input class="form-control" style="width:250px" placeholder="EmailId" type="text" ng-model="NewInsert.NewUsers.email" name="pEmailid">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            First Name
                        </td>
                        <td stheight="">
                            <input type="text" style="width:250px" class="form-control" ng-model="NewInsert.NewUsers.firstname" name="pFirstname">
                        </td>

                    </tr>
                    <tr>
                        <td>

                            Second Name
                        </td>
                        <td>
                            <input type="text" style="width:250px" class="form-control" placeholder="Second Name" ng-model="NewInsert.NewUsers.secondname" name="pSecondName">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Password
                        </td>
                        <td>
                            <input type="password" style="width:250px" class="form-control" ng-model="NewInsert.NewUsers.password">
                        </td>
                    </tr>

                    <tr>
                        <td>
                            Telephone
                        </td>
                        <td>
                            <input type="text" style="width:250px" class="form-control" ng-model="NewInsert.NewUsers.Telephoneno" name="pTelephoneno">
                        </td>
                    </tr>
                    <tr>


                        <td>
                            <label for="file">Upload your photos :</label>
                        </td>
                        <td>
                            <input class="form-control" type="file" onchange="angular.element(this).scope().LoadFileData(event)" ng-model="NewInsert.NewUsers.Image_User" style="width:250px">
                            <img id="NewInsert.NewUsers.Image_User" ng-src="{{NewInsert.NewUsers.Image_User}}" style="height:100px; width:250px">
                        </td>
                    </tr>
                    <tr>

                        <td>
                            <input type="button" class="btn btn-success" value="Update" id="btnUpdate" ng-show="editupdate" ng-click="Update()" />
                        </td>

                        <td>
                            <input type="button" class="btn btn-success" value="Submit" id="btnSubmit" ng-show="editAdd" ng-click="Submit()" />
                        </td>
                    </tr>




                </table>

                <br />

                <br />
            </div>

            <input type="button" class="btn btn-primary" value="Add Record" id="btnAdd" ng-model="AddRec" ng-click="AddRecord()">
            <br /><br />
            <table class="table table-striped" border="1" style="border-color:lightgray;">
                <thead style="background-color:lightgray;">
                    <tr>
                        <th class="col-md-2">User Id</th>
                        <th class="col-md-3">username</th>
                        <th class="col-md-3">Email Address</th>
                        <th class="col-md-3">Actions</th>
                    </tr>

                </thead>
                <tbody>
                    <tr ng-repeat="usrd in userDetails">


                        <td>{{usrd.userid}} </td>


                        <td>{{usrd.username}}</td>
                        <td>{{usrd.email}}</td>
                        <td>
                            <input type="button" class="btn btn-success" value="Edit Record" id="btnEdit" ng-model="editupdate" ng-click="EditRecord(usrd)">

                            <input type="button" class="btn btn-danger" value="Delete" id="btnDelete" ng-click="removeRec(usrd)" />
                        </td>
                    </tr>
                </tbody>

            </table>

        </div>

    </div>

}