ERPMBA/Controllers/ProcurementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERPMBA.Controllers
{
    public class ProcurementController : Controller
    {
        //
        // GET: /Procorment/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult IndexResult()
        {
            return PartialView("IndexResult");

        }



    }
}

ERPMBA/Views/Procurement/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Style/MasterPage.cshtml";
}

@section featured
    {
    <ul class="nav nav-pills">
        <li style="width: 200px; background-color: #ff5c33; text-align:center;">@Html.ActionLink("Customers Request", "IndexResult", "Procurement", new { @style = "color:Black;" })</li>
        <li style="width: 200px; background-color: #00cc00; text-align:center">@Html.ActionLink("Request Knowledge", "Index", "Procurement", new { @style = "color:Black;" })</li>
        <li style="width: 300px; background-color: #e6e600; text-align:center">@Html.ActionLink("Services Level Management", "Index", "Procurement", new { @style = "color:Black;" })</li>
        <li style="width: 200px; background-color: #9999ff; text-align:center">@Html.ActionLink("Surveys", "Index", "Procurement", new { @style = "color:Black;" })</li>
       <li style="width: 200px; background-color: #ff99ff; text-align:center">@Html.ActionLink("Tools", "Index", "Procurement", new { @style = "color:Black;" })</li>
       </ul>
       }

ERPMBA/Views/Procurement/IndexResult.cshtml
@{
    ViewBag.Title = "IndexResult";
}
@Html.Partial("Index")
<h2>Procurment1</h2>