ERPMBA/Models/CompositeItems.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ERPMBA.Models
{
    public class CompositeItems
    {
        public string Name { get; set; }
        public string SKU { get; set; }
        public string Unit { get; set; }
        public string Item { get; set; }
        public string Quantity { get; set; }
        public string Itemsellingprice { get; set; }
        public string Itempurchaseprice { get; set; }
        public string UPC { get; set; }
        public string MPN { get; set; }
        public string EAN { get; set; }
        public string ISBN { get; set; }
        public string SellingPrice { get; set; }
        public string PurchasePrice { get; set; }
        public string SalesAcc { get; set; }
        public string PurchaseAcc { get; set; }
        public string SalesDesc { get; set; }
        public string PurchaseDesc { get; set; }
        public string Preffervend { get; set; }
        public string InventAcc { get; set; }
        public string ReorderLevel { get; set; }
        public string OpeningStock { get; set; }
        public string Openingstckval { get; set; }
    }
}

ERPMBA/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ERPMBA.Models
{
    public class Customer
    {
    }
}

ERPMBA/Models/ItemAdjustments.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ERPMBA.Models
{
    public class ItemAdjustments
    {
        public string AdjustMode { get; set; }
        public string Reference { get; set; }
        public DateTime Date { get; set; }
        public string Account { get; set; }
        public string Reason { get; set; }
        public string Description { get; set; }
        public string Itemdetails { get; set; }
        public int Quantityavail { get; set; }
        public int Newquantity { get; set; }
        public int Quantityadjust { get; set; }

    }
}

ERPMBA/Models/ItemGroups.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ERPMBA.Models
{
    public class ItemGroups
    {
        public string Type { get; set; }
        public string Itemgroupname { get; set; }
        public string Description { get; set; }
        public string Unit { get; set; }
        public string Manufacturer { get; set; }
        public string Brand { get; set; }
        public string Multipleitems { get; set; }
        public string Attribute { get; set; }
        public string Options { get; set; }
        public string Itemtype { get; set; }
        public string Itemname { get; set; }
        public string SKU { get; set; }
        public string PurchasePrice { get; set; }
        public string SellingPrice { get; set; }
        public string UPC { get; set; }
        public string EAN { get; set; }
        public string ISBN { get; set; }
        public string ReorderLevel { get; set; }
        public string SalesAccount { get; set; }
        public string PurchaseAccount { get; set; }
        public string InventoryAccount { get; set; }



    }
}

ERPMBA/Models/Manufacturer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ERPMBA.Models
{
    public class Manufacturer
    {
        public string Manufacturername { get; set; }
        public string Unitno { get; set; }

    }
}

ERPMBA/Models/Transferorder.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ERPMBA.Models
{
    public class Transferorder
    {
        public string Empid { get; set; }
        public string Empname { get; set; }
        public string Emailid { get; set; }
    }
}

ERPMBA/Models/Unit.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ERPMBA.Models
{
    public class Unit
    {
        public string Itemname { get; set; }
        public string Itemgroupname { get; set; }
        public string Unitno { get; set; }

    }
}

ERPMBA/Controllers/HRController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERPMBA.Controllers
{
    public class HRController : Controller
    {
        //
        // GET: /HR/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ERPMBA/Controllers/IntegrationUnitController.cs
using ERPMBA.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERPMBA.Controllers
{
    public class IntegrationUnitController : Controller
    {
        //
        // GET: /IntegrationUnit/

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult UserAdmin()
        {
            return View();
        }
        public ActionResult ItemAdmin()
        {
            return View();

        }
        public ActionResult CustomerAdmin()
        {
            return View();

        }
        public ActionResult SupplierAdmin()
        {
            return View();

        }
        public ActionResult HRAdmin()
        {
            return View();

        }
        public ActionResult UserInf()
        {

            return View();

        }

        public ActionResult HR()
        {

            return View();

        }

        public ActionResult Customer()
        {

            return View();

        }

         public JsonResult GetNewCustomerInfo()
        {
            DbCustomer dbcont = new DbCustomer();
            List<NewCustomer> ListofUser = dbcont.NewCustomers.ToList();


            return Json(ListofUser, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        public string InsertNewCustomer(NewCustomer usr1)
        {
            DbCustomer dbcont = new DbCustomer();
            var usr = new NewCustomer();

           
            usr.CustomerName = usr1.CustomerName;
            usr.Companyname = usr1.Companyname;
            usr.Contactdisplayname = usr1.Contactdisplayname;
            usr.Email = usr1.Email;
            usr.Companymail = usr1.Companymail;
            usr.Phoneno = usr1.Phoneno;
            usr.Mobileno = usr1.Mobileno;
            usr.Skype = usr1.Skype;
            usr.Designation = usr1.Designation;
            usr.Department = usr1.Department;
            usr.Website = usr1.Website;
            usr.Street1 = usr1.Street1;
            usr.Street2 = usr1.Street2;
            usr.City = usr1.City;
            usr.States = usr1.States;
            usr.Zipcode = usr1.Zipcode;
            usr.Country = usr1.Country;
            usr.Currency = usr1.Currency;
            usr.Payment = usr1.Payment;
            dbcont.NewCustomers.Add(usr);
            dbcont.SaveChanges();

            return "Customer Updated";

        }

        [HttpPost]
        public string UpdateNewCustomer(NewCustomer usr1)
        {

            if (usr1 != null)
            {
                using (DbCustomer dataContext = new DbCustomer())
                {
                    var no = usr1.CustomerID;
                    var usr = dataContext.NewCustomers.Where(x => x.CustomerID == no).FirstOrDefault();


                    usr.CustomerName = usr1.CustomerName;
                    usr.Companyname = usr1.Companyname;
                    usr.Contactdisplayname = usr1.Contactdisplayname;
                    usr.Email = usr1.Email;
                    usr.Companymail = usr1.Companymail;
                    usr.Phoneno = usr1.Phoneno;
                    usr.Mobileno = usr1.Mobileno;
                    usr.Skype = usr1.Skype;
                    usr.Designation = usr1.Designation;
                    usr.Department = usr1.Department;
                    usr.Website = usr1.Website;
                    usr.Street1 = usr1.Street1;
                    usr.Street2 = usr1.Street2;
                    usr.City = usr1.City;
                    usr.States = usr1.States;
                    usr.Zipcode = usr1.Zipcode;
                    usr.Country = usr1.Country;
                    usr.Currency = usr1.Currency;
                    usr.Payment = usr1.Payment;
                    dataContext.SaveChanges();
                    return "Customer Updated";
                }
            }
            else
            {
                return "Invalid Customer";
            }
        }
        public string DeleteNewCustomer(NewCustomer usrd)
        {
            if (usrd != null)
            {
                using (DbCustomer dbcont = new DbCustomer())
                {
                    var no = usrd.CustomerID;
                    var UserList = dbcont.NewCustomers.Where(x => x.CustomerID == no).FirstOrDefault();
                    dbcont.NewCustomers.Remove(UserList);
                    dbcont.SaveChanges();
                    return "Customer Deleted";
                }
            }
            else
            {
                return "Invalid Customer";
            }
        }
       
       
        
       
        public ActionResult Login()
        {
            return View();
        }
        public ActionResult ItemGroups()
        {
            return View();
        }
        

        public ActionResult CompositeItems()
        {
            return View();
        }
        public ActionResult ItemAdjustments()
        {
            return View();
        }
        public ActionResult TransferOrders()
        {
            return View();
        }
        public ActionResult Unit()
        {
            return View();
        }
        public ActionResult Manufacturer()
        {
            return View();
        }
       

    }
}

ERPMBA/Views/IntegrationUnit/CompositeItems.cshtml
@model ERPMBA.Models.CompositeItems

@{
    ViewBag.Title = "CompositeItems";
}
@Html.Partial("ItemAdmin")
<div style="float:left; width:60%;height:100%;padding-top:40px;padding-left:0px;">
    <div id="Address" style="width:100%;height:525px;">

        <form name="contactForm" method="post" action="" class="in-line" role="form">


            <h3> New Composite Item</h3>
            <hr />

            <table>
                <tr>
                    <td> Name</td>
                    <td>
                        <input type=text name=textnames id="name" size="30" class="form-control">
                    </td>

                </tr>
                <tr>
                    <td>
                        SKU<span class="glyphicon glyphicon-question-sign" title="Stock Keeping Unit"></span>
                    </td>
                    <td>

                        <input type=text name=textnames id="textname" size="30" class="form-control">
                    </td>
                </tr>
                <tr>
                    <td>Unit<span class="glyphicon glyphicon-question-sign" title="Unit of Measurement"></span></td>
                    <td>

                        <select name="unit" style="width:265px;height:35px" class="form-control">
                            <option> Select Unit</option>
                            <option></option>
                            <option></option>
                            <option></option>
                            <option></option>
                        </select>

                    </td>
                </tr>
                <tr>
                    <td>UPC<span class="glyphicon glyphicon-question-sign" title="Universal Product Code(12-digit)"></span></td>

                    <td>

                        <input type=text name=textnames id="textname" size="30" class="form-control">
                    </td>
                </tr>
                <tr>



                    <td>MPN<span class="glyphicon glyphicon-question-sign" title="Manufacturing Port Number"></span></td>

                    <td>

                        <input type=text name=textnames id="textname" size="30" class="form-control">
                    </td>
                </tr>
                <tr>
                    <td>EAN<span class="glyphicon glyphicon-question-sign" title="International Article Number"></span></td>
                    <td>

                        <input type=text name=textnames id="textname" size="30" class="form-control">
                    </td>
                </tr>
                <tr>
                    <td>ISBN<span class="glyphicon glyphicon-question-sign" title="International Standard Book Number"></span></td>
                    <td>

                        <input type=text name=textnames id="textname" size="30" class="form-control">
                    </td>
                </tr>
            </table>
        </form>
        <br />
        <h4>Associate Items</h4><hr />
        <div ng-app="myapp" ng-controller="ListController">
            <div class="container">
                <div class="row">
                    <div class="col-md-8">

                        <div class="panel-body">
                            <form ng-submit="addNew()">
                                <table class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th><input type="checkbox" ng-model="selectedAll" ng-click="checkAll()" /></th>
                                            <th>Item </th>
                                            <th>Quantity</th>
                                            <th>Selling Price</th>
                                            <th>Purchase Price</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr ng-repeat="personalDetail in personalDetails">
                                            <td>
                                                <input type="checkbox" ng-model="personalDetail.selected" />
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" ng-model="personalDetail.item" required />
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" ng-model="personalDetail.quantity" required />
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" ng-model="personalDetail.sellingprice" required />
                                            </td>
                                            <td>
                                                <input type="text" class="form-control" ng-model="personalDetail.purchaseprice" required />
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div class="form-group">
                                    <input ng-hide="!personalDetails.length" type="button" class="btn btn-danger pull-right" ng-click="remove()" value="Remove">
                                    <input type="submit" class="btn btn-primary addnew pull-right" value="Add New">
                                </div>
                            </form>
                        </div>

                    </div>
                </div>
            </div>
        </div>


        <script>
var app = angular.module("myapp", []);
	app.controller("ListController", ['$scope', function($scope) {
	    $scope.personalDetails = [
	        {
	            'item': '',
	            'quantity': '',
	            'sellingprice': '',
	            'purchaseprice': ''
	        },
	        {
	            'item': '',
	            'quantity': '',
	            'sellingprice': '',
	            'purchaseprice': ''
	        },
	        {
	            'item': '',
	            'quantity': '',
	            'sellingprice': '',
	            'purchaseprice': ''
	        }];

	        $scope.addNew = function(personalDetails){
	            $scope.personalDetails.push({
	                'item': " ",
	                'quantity': " ",
	                'sellingprice': " ",
	                'purchaseprice': " ",
	            });
	            $scope.PD = {};
	        };

	        $scope.remove = function(){
	            var newDataList=[];
	            $scope.selectedAll = false;
	            angular.forEach($scope.personalDetails, function(selected){
	                if(!selected.selected){
	                    newDataList.push(selected);
	                }
	            });
	            $scope.personalDetails = newDataList;
	        };

	        $scope.checkAll = function () {
	            if (!$scope.selectedAll) {
	                $scope.selectedAll = true;
	            } else {
	                $scope.selectedAll = false;
	            }
	            angular.forEach($scope.personalDetails, function (personalDetails) {
	                personalDetails.selected = $scope.selectedAll;
	            });
	        };
	}]);
        </script>
        <h4>Sales Information</h4>
        <hr />
        <form>


            <table>
                <tr>
                    <td>Selling Price</td>
                    <td><input type=text name=textnames id="textname" size="30" class="form-control"></td>


                </tr>
                <tr>
                    <td>Account<span class="glyphicon glyphicon-question-sign" title="All transactions related to items you sell will be displayed in this account"></span></td>
                    <td>
                        <select name="salesacc" style="width:265px " class="form-control">
                            <option>Sales</option>
                            <option></option>
                            <option></option>
                            <option></option>
                            <option></option>
                        </select>
                    </td>

                </tr>

                <tr>

                    <td>
                        Description
                    </td>
                    <td>
                        <textarea rows="3" cols="27" class="form-control"> </textarea>
                    </td>

                </tr>
            </table>
        </form>

        <h4>Purchase Information</h4>
        <hr />
        <form>

            <table>
                <tr>
                    <td>Purchase Price</td>
                    <td><input type=text name=textnames id="textname" size="30" class="form-control"></td>


                </tr>
                <tr>
                    <td>Account<span class="glyphicon glyphicon-question-sign" title="All transactions related to items you buy will be displayed in this account"></span></td>
                    <td>
                        <select name="salesacc" style="width:265px " class="form-control">
                            <option>Cost of Goods Sold</option>
                            <option></option>
                            <option></option>
                            <option></option>
                            <option></option>
                        </select>
                    </td>

                </tr>

                <tr>

                    <td>
                        Description
                    </td>
                    <td>
                        <textarea rows="3" cols="27" class="form-control"> </textarea>
                    </td>

                </tr>

                <tr>

                    <td>Preferred Vendor</td>
                    <td>
                        <select name="salesacc" style="width:265px" class="form-control">
                            <option></option>
                            <option></option>
                            <option></option>
                            <option></option>
                            <option></option>
                        </select>
                    </td>
                </tr>
            </table>
        </form>
        <h4>Additional Information</h4>
        <hr />

        <form>
            <table>

                <tr>
                    <td>Inventory Account<span class="glyphicon glyphicon-question-sign" title="All Inventory related transactions"></span></td>
                    <td>
                        <select name="salesacc" style="width:265px;height:35px" class="form-control">
                            <option></option>
                            <option></option>
                            <option></option>
                            <option></option>
                            <option></option>
                        </select>
                    </td>
                </tr>
                <tr>
                    <td>Opening Stock</td>

                    <td>

                        <input type=text name=textnames id="textname" size="30" class="form-control">
                    </td>
                </tr>
                <tr>
                    <td>Reorder Level</span></td>

                    <td>

                        <input type=text name=textnames id="textname" size="30" class="form-control">
                    </td>
                </tr>
                <tr>
                    <td>Opening Stock Value</td>

                    <td>

                        <input type=text name=textnames id="textname" size="30" class="form-control">
                    </td>
                </tr>
                <tr>

                    <td>
                        <button id="submit" name="submit" class="btn btn-primary" value="1">Save</button>
                    </td>
                    <td>
                        <button id="cancel" name="cancel" class="btn btn-primary" value="1">Cancel</button>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>

ERPMBA/Views/IntegrationUnit/CustomerAdmin.cshtml
@{
    ViewBag.Title = "CustomerAdmin";
}
@Html.Partial("Index")
<div style="float:left; width:200px; padding-top:100px; border-color:#333300">
    <ul class="nav nav-pills nav-stacked" style="float:left;">
        <li style="width: 200px;background : linear-gradient(to right, #ccffff, #eaecc6 100%); text-align:center">@Html.ActionLink("Customer", "Customer", "Administrator", new { @style = "color:Black;" })</li>
        <li style="width: 200px; background : linear-gradient(to right, #ccffff, #eaecc6 100%);text-align:center">@Html.ActionLink("Category", "", "Administrator", new { @style = "color:Black;" })</li>
        <li style="width: 200px;background : linear-gradient(to right, #ccffff, #eaecc6 100%); text-align:center">@Html.ActionLink("Role", "", "Administrator", new { @style = "color:Black;" })</li>
        
    </ul>
</div>

ERPMBA/Views/IntegrationUnit/HRAdmin.cshtml
@{
    ViewBag.Title = "HRAdmin";
}

 @Html.Partial("Index")  
 <div style="float:left; width:200px; padding-top:100px; border-color:#333300">
  <ul class="nav nav-pills nav-stacked" style=" float:left; background-color:Black">
  <li class="active" style="width:200px;  text-align:center; "><a data-toggle="tab" href="#home" style="background-color:#003366;color:White" >New Hr</a></li>
  <li  style="width: 200px;   text-align:center"><a data-toggle="tab" href="#menu1" style="background-color: #00cc00;color:White">Catagory</a></li>
  <li style="width: 200px;text-align:center"><a data-toggle="tab" href="#menu2" style="background-color: #e6e600;color:#333300 ">Role</a></li>
  <li style="width: 200px;  text-align:center"><a data-toggle="tab" href="#menu3" style="background-color: #ff3300;color:White">Setting 1</a></li>
  <li style="width: 200px; text-align:center"><a data-toggle="tab" href="#menu4" style="background-color: #0000ff;color:White">Setting 2</a></li>
</ul>
</div>

<div class="tab-content" style="  float:left; width:60%;height:550px;border-style: solid;border-color:#8c8c8c;background-color:#f2f2f2;background-color:#f2f2f2;">
  <div id="home" class="tab-pane fade in active"   style="color: #ff5c33; width:100%;height:525px;">
  <center>  <h3>New HR</h3>
    <p>Pages Will Be Shortly Publiced</p>
    
 </center>
  </div>
  <div id="menu1" class="tab-pane fade"  style="color: #00cc00; width:100%;height:525px;">
    <h3>HR Catagory</h3>
    <p>Pages Will Be Shortly Publiced</p>
    
 
  </div>
  <div id="menu2" class="tab-pane fade" style="color: #997a00; width:100%;height:525px;">
    <h3>HR Role</h3>
    <p>Pages Will Be Shortly Publiced</p>
  </div>
  <div id="menu3" class="tab-pane fade" style="color: #9999ff; width:100%;height:525px;">
    <h3>HR Setting 1</h3>
    <p>Pages Will Be Shortly Publiced</p>
  </div>
  <div id="menu4" class="tab-pane fade" style="color: #b300b3; width:100%;height:525px;">
    <h3>HR Setting 2</h3>
    <p>Pages Will Be Shortly Publiced</p>
  </div>
</div>

ERPMBA/Views/IntegrationUnit/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Style/MasterPage.cshtml";


}
@section featured{
    <script src="~/Scripts/Transferorderscript.js"></script>




    <ul class="nav nav-pills" style="background: linear-gradient(to right, #e1eec3, #f05053);">
        <li style="width: 200px;  text-align:center">@Html.ActionLink("Item", "ItemAdmin", "IntegrationUnit", new { @style = "color:Black;" })</li>
        <li style="width: 200px;  text-align:center">@Html.ActionLink("Customer", "CustomerAdmin", "IntegrationUnit", new { @style = "color:Black;" })</li>
        <li style="width: 200px;  text-align:center">@Html.ActionLink("Supplier", "SupplierAdmin", "IntegrationUnit", new { @style = "color:Black;" })</li>
    </ul>

}

ERPMBA/Views/IntegrationUnit/ItemAdmin.cshtml
@{
    ViewBag.Title = "ItemAdmin";
}
@Html.Partial("Index")
<div style="float:left; width:200px; padding-top:100px; border-color:#333300">
    <ul class="nav nav-pills nav-stacked" style="float:left;">
        <li style="width: 200px;background : linear-gradient(to right, #ccffff, #eaecc6 100%); text-align:center">@Html.ActionLink("Item Groups", "ItemGroups", "Administrator", new { @style = "color:Black;" })</li>
        <li style="width: 200px; background : linear-gradient(to right, #ccffff, #eaecc6 100%);text-align:center">@Html.ActionLink("Items", "Items", "Administrator", new { @style = "color:Black;" })</li>
        <li style="width: 200px;background : linear-gradient(to right, #ccffff, #eaecc6 100%); text-align:center">@Html.ActionLink("Brand", "Brand", "Administrator", new { @style = "color:Black;" })</li>
        <li style="width: 200px; background : linear-gradient(to right, #ccffff, #eaecc6 100%); text-align:center">@Html.ActionLink("Category", "ItemAdjustments", "Administrator", new { @style = "color:Black;" })</li>
    </ul>
</div>

ERPMBA/Views/IntegrationUnit/ItemGroups.cshtml
@model ERPMBA.Models.ItemGroups

@{
    ViewBag.Title = "ItemGroups";
}
@Html.Partial("ItemAdmin")
<div style="float:left; width:60%;height:100%;padding-top:40px;padding-left:0px;">
    <div id="Address" style="width:100%;height:525px;">

        <form name="contactForm" method="post" action="" class="form-horizontal" role="form">


            <h3> New Item Group</h3>

            <hr />
            <table>
                <tr>
                    <td>
                        Type
                    </td>
                    <td>
                        <div class="input-group">


                            <input type="radio" name="Type" value="product" />Product&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="Type" value="Service" />Service


                        </div>
                    </td>
                </tr>
                <tr>
                    <td>Item Group Name</td>
                    <td>
                        <input type=text name=textnames id="textname" size="30" class="form-control">
                    </td>

                </tr>
                <tr>
                    <td>Description</td>
                    <td>

                        <input type=text name=textnames id="textname" size="30" class="form-control">
                    </td>
                </tr>
                <tr>
                    <td>Unit</td>
                    <td>
                        <select name="unit" style="width:265px;height:35px;" class="form-control">
                            <option>Select Unit</option>
                            <option></option>
                            <option></option>
                            <option></option>
                            <option></option>
                        </select>
                    </td>


                </tr>
                <tr>
                    <td>Manufacturer</td>
                    <td>

                        <select name="mnfcr" style="width:265px;height:35px;" class="form-control">
                            <option>Select Manufacturer</option>
                            <option></option>
                            <option></option>
                            <option></option>
                            <option></option>
                        </select>
                    </td>
                <tr>
                    <td>Brand</td>
                    <td>

                        <select name="brnd" style="width:265px;height:35px;" class="form-control">
                            <option>Select Brand</option>
                            <option></option>
                            <option></option>
                            <option></option>
                            <option></option>
                        </select>
                    </td>
                </tr>

                <tr>
                    <td>Multiple Items</td>
                    <td>

                        <input type="checkbox" value="">Create Attributes & Options


                    </td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        Atrribute
                        <select name="attr" style="width:244px;height:35px;" class="form-control">
                            <option>eg:color</option>
                            <option></option>
                            <option></option>
                            <option></option>
                            <option></option>
                        </select>
                    </td>
                    <td>
                        Options
                        <select name="opts" style="width:244px;height:35px;" class="form-control">
                            <option></option>
                            <option></option>
                            <option></option>
                            <option></option>
                            <option></option>
                        </select>
                    </td>
                </tr>


            </table>
        </form>
    </div>
</div>

ERPMBA/Views/IntegrationUnit/Manufacturer.cshtml
@{
    ViewBag.Title = "Manufacturer";
}

<h2>Manufacturer</h2>

ERPMBA/Views/IntegrationUnit/TransferOrders.cshtml
@{
    ViewBag.Title = "TransferOrders";
}

<h2>TransferOrders</h2>

ERPMBA/Views/IntegrationUnit/UserInf2.cshtml
@{
    ViewBag.Title = "~/Administrator/Index2.cshtml";
    Layout = "~/Views/Style/MasterPage.cshtml";
    
}

  @section MySubScr1{
   
     
     This is just test
    
    }